### ISSUE TITLE
IDM fails to start on Java 17

### ISSUE THREAD

**Issue by karelmaxa** [WrenSecurity/wrenidm#123]
In this moment Wren:IDM fails to start on Java 17 (`openjdk 17.0.2 2022-01-18`) with the default configuration project. Reported exceptions:

<details>
<summary>java.lang.NoClassDefFoundError: javax/transaction/TransactionManager</summary>

```
org.apache.felix.log.LogException: org.osgi.framework.BundleException: Activator start error in bundle org.apache.servicemix.transaction [4].
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2452)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.felix.log.LogException: java.lang.NoClassDefFoundError: javax/transaction/TransactionManager
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2344)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClassParallel(BundleWiringImpl.java:2162)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2096)
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1565)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2344)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClassParallel(BundleWiringImpl.java:2162)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2096)
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1565)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at org.apache.servicemix.transaction.TransactionManagerService.<init>(TransactionManagerService.java:146)
        at org.apache.servicemix.transaction.Activator.updated(Activator.java:81)
        at org.apache.servicemix.transaction.Activator.start(Activator.java:49)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
        ... 4 more
Caused by: java.lang.ClassNotFoundException: javax.transaction.TransactionManager
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:1179)
        at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1618)
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1548)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 27 more
```
</details>

<details>
<summary>java.lang.IllegalStateException: Unknown protocol: http</summary>

```
SEVERE: Bundle: org.forgerock.openidm.repo-jdbc [9] FrameworkEvent ERROR
org.apache.felix.log.LogException: org.osgi.framework.BundleException: Activator start error in bundle org.forgerock.openidm.repo-jdbc [9].
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2452)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.felix.log.LogException: java.lang.ExceptionInInitializerError: null
        at java.base/javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:66)
        at java.base/javax.crypto.Cipher.<init>(Cipher.java:275)
        at java.base/com.sun.crypto.provider.CipherForKeyProtector.<init>(KeyProtector.java:436)
        at java.base/com.sun.crypto.provider.KeyProtector.unseal(KeyProtector.java:398)
        at java.base/com.sun.crypto.provider.JceKeyStore.engineGetKey(JceKeyStore.java:146)
        at java.base/java.security.KeyStore.getKey(KeyStore.java:1050)
        at org.forgerock.openidm.keystore.impl.DefaultKeyStoreInitializer.initializeKeyStore(DefaultKeyStoreInitializer.java:89)
        at org.forgerock.openidm.keystore.impl.KeyStoreServiceImpl.activate(KeyStoreServiceImpl.java:82)
        at org.forgerock.openidm.keystore.factory.KeyStoreServiceFactory.getInstance(KeyStoreServiceFactory.java:45)
        at org.forgerock.openidm.crypto.factory.CryptoServiceFactory.getInstance(CryptoServiceFactory.java:52)
        at org.forgerock.openidm.config.persistence.ConfigBootstrapHelper.getBootConfig(ConfigBootstrapHelper.java:118)
        at org.forgerock.openidm.config.persistence.ConfigBootstrapHelper.getRepoBootConfig(ConfigBootstrapHelper.java:146)
        at org.forgerock.openidm.repo.jdbc.impl.Activator.start(Activator.java:51)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
        ... 4 more
Caused by: org.apache.felix.log.LogException: java.lang.RuntimeException: java.net.MalformedURLException: Unknown protocol: http
        at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:248)
        ... 19 more
Caused by: org.apache.felix.log.LogException: java.net.MalformedURLException: Unknown protocol: http
        at java.base/java.net.URL.<init>(URL.java:708)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:246)
        ... 19 more
Caused by: java.lang.IllegalStateException: Unknown protocol: http
        at org.apache.felix.framework.URLHandlersStreamHandlerProxy.parseURL(URLHandlersStreamHandlerProxy.java:373)
        at java.base/java.net.URL.<init>(URL.java:703)
        ... 22 more
```
</details>

<details>
<summary>java.lang.NoClassDefFoundError: Could not initialize class javax.crypto.JceSecurityManager</summary>

```
SEVERE: Bundle: org.forgerock.openidm.keystore [17] bundle org.forgerock.openidm.keystore:6.1.0.SNAPSHOT (17)[org.forgerock.openidm.keystore.impl.KeyStoreServiceImpl(5)] : The activate method has thrown an exception
java.lang.NoClassDefFoundError: Could not initialize class javax.crypto.JceSecurityManager
        at java.base/javax.crypto.Cipher.<init>(Cipher.java:275)
        at java.base/com.sun.crypto.provider.CipherForKeyProtector.<init>(KeyProtector.java:436)
        at java.base/com.sun.crypto.provider.KeyProtector.unseal(KeyProtector.java:398)
        at java.base/com.sun.crypto.provider.JceKeyStore.engineGetKey(JceKeyStore.java:146)
        at java.base/java.security.KeyStore.getKey(KeyStore.java:1050)
        at org.forgerock.openidm.keystore.impl.DefaultKeyStoreInitializer.initializeKeyStore(DefaultKeyStoreInitializer.java:89)
        at org.forgerock.openidm.keystore.impl.KeyStoreServiceImpl.activate(KeyStoreServiceImpl.java:82)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:244)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:685)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:529)
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318)
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:776)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437)
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:667)
        at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:305)
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:554)
        at org.apache.felix.scr.impl.Activator.access$200(Activator.java:70)
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:421)
        at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:420)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
        at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
        at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
        at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4817)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2336)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

**Comment by karelmaxa** [comment]
Support for Java 17 was added in the pull request [#129]. Wren:IDM starts successfully on *OpenJDK Runtime Environment Temurin-17.0.4.1+1*.
