### ISSUE TITLE
NPE when any exception is thrown during CREATE operation in reconciliation

### ISSUE THREAD

**Issue by karelmaxa** [WrenSecurity/wrenidm#126]
When any exception occurs during CREATE operation in reconciliation, bellow NPE exception is thrown. As a result of this exception the reconciliation is stopped and marked as failed. Also the relevant source entry is not logged into audit recon log.

In this [place](https://github.com/WrenSecurity/wrenidm/blob/master/openidm-core/src/main/java/org/forgerock/openidm/sync/impl/SyncOperation.java#L448) is created `targetObjectAccessor` but `localId` can be null (e.g. when it is generated by the target system). In this [place](https://github.com/WrenSecurity/wrenidm/blob/master/openidm-core/src/main/java/org/forgerock/openidm/sync/impl/SourceRecon.java#L99) is set `targetObjectId` to the audit recon log, source operation has loaded target object (from the mapping script) but `localId` is null.

Related NPE exception stacktrace:

```
org.forgerock.openidm.sync.impl.ObjectMapping logReconEnd
INFO: Reconciliation failed. SOURCE_IGNORED: xx UNASSIGNED: xx AMBIGUOUS: xx CONFIRMED: xx FOUND_ALREADY_LINKED: xx UNQUALIFIED: xx ABSENT: xx TARGET_IGNORED: xx SOURCE_MISSING: xx MISSING: xx FOUND: xx 
org.forgerock.openidm.sync.impl.ReconciliationService$1 run
INFO: Reconciliation reported exception
org.forgerock.openidm.sync.SynchronizationException: Synchronization failed
        at org.forgerock.openidm.sync.impl.ObjectMapping.doRecon(ObjectMapping.java:840)
        at org.forgerock.openidm.sync.impl.ObjectMapping.recon(ObjectMapping.java:687)
        at org.forgerock.openidm.sync.impl.ReconciliationService.reconcile(ReconciliationService.java:399)
        at org.forgerock.openidm.sync.impl.ReconciliationService.access$000(ReconciliationService.java:91)
        at org.forgerock.openidm.sync.impl.ReconciliationService$1.run(ReconciliationService.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: org.forgerock.openidm.sync.SynchronizationException: Exception in executing recon task: null
        at org.forgerock.openidm.sync.impl.ReconFeeder.translateTaskThrowable(ReconFeeder.java:120)
        at org.forgerock.openidm.sync.impl.ReconFeeder.execute(ReconFeeder.java:97)
        at org.forgerock.openidm.sync.impl.ObjectMapping.doRecon(ObjectMapping.java:789)
        ... 7 more
Caused by: java.lang.NullPointerException
        at java.net.URLEncoder.encode(URLEncoder.java:204)
        at org.forgerock.openidm.sync.impl.LazyObjectAccessor.qualifiedId(LazyObjectAccessor.java:169)
        at org.forgerock.openidm.sync.impl.SourceRecon.recon(SourceRecon.java:99)
        at org.forgerock.openidm.sync.impl.ReconTask.call(ReconTask.java:62)
        at org.forgerock.openidm.sync.impl.ReconTask.call(ReconTask.java:32)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
```

**Comment by MarkkuPekkarinen** [comment]
I encountered a similar problem , caused by a Link Qualifier that was left in the global position , the problem went away when I changed it to Link Qualifier: default

**Comment by karelmaxa** [comment]
@MarkkuPekkarinen It is probably something different. The reported exception is thrown when creating audit recon log entry and there is no target object identifier (it is created by target system by CREATE operation failed). Could you please provide more information (e.g. stacktrace)?
