### ISSUE TITLE
Tests in openidm-launcher module does not work on Windows

### ISSUE THREAD

**Issue by pavelhoral** [WrenSecurity/wrenidm#168]
Module openidm-launcher is glob matcher from plexus-utils library. This library is no longer maintained and is sensitive to path separator characters (`\` vs `/`). Fortunately the base configuration does not need to use path separator so the question is if we really need that feature. Nevertheless the unit test `ConfigurationUtilTest` does not work when `File.separator == "\\"` (that also means Wren:IDM would not run on Windows if someone tries to use path separator in glob pattern inside `launcher.json` includes/excludes).

Also with our Java 11+ support we can switch glob matching to native PathMatcher and possible drop the dependency (if it is used only for this purpose).

```
FAILED: org.forgerock.commons.launcher.ConfigurationUtilTest.testGetZipFileListing
java.lang.AssertionError: Find all jar files expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:472)
	at org.forgerock.commons.launcher.ConfigurationUtilTest.testGetZipFileListing(ConfigurationUtilTest.java:69)
```

**Comment by pavelhoral** [comment]
I think this issue can be generalized to "Windows build does not work". There are more modules that fail.

**Comment by pavelhoral** [comment]
JRE's PathMatcher does not handle directory wildcards `**` the same as Plexus Utils' MatchPattern does:

```java
var plexusMatch = MatchPattern.fromString("**\\hello\\**\\*.jar").matchPath("hello\\foo.jar", false); // => true
var javaMatch = FileSystems.getDefault().getPathMatcher("glob:**/hello/**/*.jar").matches(Path.of("hello\\foo.jar")); // => false
```

JRE must match `**` to *at least one* directory whereas Plexus Utils can match *zero or more*. So if we want to keep the old behavior we might need to write our own matcher :(.

**Comment by pavelhoral** [comment]
This has been solved by the linked PR.
