### ISSUE TITLE
IDM fails to start on Java 10

### ISSUE THREAD

**Issue by pavelhoral** [WrenSecurity/wrenidm#59]
Right now IDM is not compatible with Java 10:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.util.SecureAction (file:/tmp/openidm/bin/felix.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.util.SecureAction
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" org.osgi.framework.BundleException: Could not create bundle object.
        at org.apache.felix.framework.Felix.installBundle(Felix.java:3057)
        at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
        at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:140)
        at org.forgerock.commons.launcher.AbstractOSGiFrameworkService.process(AbstractOSGiFrameworkService.java:177)
        at org.forgerock.commons.launcher.AbstractOSGiFrameworkService.process(AbstractOSGiFrameworkService.java:160)
        at org.forgerock.commons.launcher.AbstractOSGiFrameworkService.start(AbstractOSGiFrameworkService.java:87)
        at org.forgerock.commons.launcher.Main.main(Main.java:38)
Caused by: java.lang.UnsupportedOperationException: Unable to add extension bundle to FrameworkClassLoader - Maybe not an URLClassLoader?
        at org.apache.felix.framework.ExtensionManager.addExtensionBundle(ExtensionManager.java:453)
        at org.apache.felix.framework.Felix.installBundle(Felix.java:3023)
        ... 6 more
```

**Comment by krystofNovotny** [comment]
Issue was resolved.
