### ISSUE TITLE
PostgreSQL JDBC driver is incompatible with PG 10+

### ISSUE THREAD

**Issue by geostarling** [WrenSecurity/wrenidm#66]
When trying to run WrenIDM 5.x sustaining branch backed by PostgreSQL DB 10.5 following errors occur during IDM startup:

```
java.io.IOException: Failed to store configuration in repository: Creating object failed after 1 attempts (0-0A000): Returning autogenerated keys is only supported for 8.2 and later servers.
        at org.forgerock.openidm.config.persistence.RepoPersistenceManager.store(RepoPersistenceManager.java:409)
        at org.apache.felix.cm.impl.CachingPersistenceManagerProxy.store(CachingPersistenceManagerProxy.java:242)
        at org.apache.felix.cm.impl.ConfigurationImpl.update(ConfigurationImpl.java:381)
        at org.apache.felix.cm.impl.ConfigurationAdapter.update(ConfigurationAdapter.java:131)
        at org.forgerock.openidm.config.installer.JSONConfigInstaller.setConfig(JSONConfigInstaller.java:338)
        at org.forgerock.openidm.config.installer.DelayedConfigHandler.addedProvider(DelayedConfigHandler.java:76)
        at org.forgerock.openidm.metadata.impl.ProviderTracker.addProvider(ProviderTracker.java:127)
        at org.forgerock.openidm.metadata.impl.ProviderTracker.addedService(ProviderTracker.java:143)
        at org.forgerock.openidm.metadata.impl.ProviderTracker.addedService(ProviderTracker.java:54)
        at org.forgerock.openidm.osgi.ServiceTrackerNotifier.addingService(ServiceTrackerNotifier.java:71)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
        at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:991)
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:839)
        at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:546)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4557)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3549)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:886)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:873)
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:132)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:940)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:740)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleDynamicCustomizer.addedService(DependencyManager.java:799)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleDynamicCustomizer.addedService(DependencyManager.java:743)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1215)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1136)
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:945)
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:881)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1167)
        at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:127)
        at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:991)
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:839)
        at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:546)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4557)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3549)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:322)
        at org.forgerock.openicf.framework.osgi.internal.Activator.start(Activator.java:86)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2226)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.forgerock.json.resource.InternalServerErrorException: Creating object failed after 1 attempts (0-0A000): Returning autogenerated keys is only supported for 8.2 and later servers.
        at org.forgerock.openidm.repo.jdbc.impl.JDBCRepoService.create(JDBCRepoService.java:359)
        at org.forgerock.openidm.config.persistence.RepoPersistenceManager.store(RepoPersistenceManager.java:401)
        ... 47 more
Caused by: org.postgresql.util.PSQLException: Returning autogenerated keys is only supported for 8.2 and later servers.
        at org.postgresql.jdbc3.AbstractJdbc3Statement.addReturning(AbstractJdbc3Statement.java:151)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.prepareStatement(AbstractJdbc3Connection.java:364)
        at org.forgerock.openidm.repo.jdbc.impl.query.TableQueries.getPreparedStatement(TableQueries.java:230)
        at org.forgerock.openidm.repo.jdbc.impl.GenericTableHandler.create(GenericTableHandler.java:245)
        at org.forgerock.openidm.repo.jdbc.impl.JDBCRepoService.create(JDBCRepoService.java:333)
        ... 48 more
```

For reasons behind this error, please see [this source](https://support.inductiveautomation.com/index.php?/Knowledgebase/Article/View/122/0/database-connection-errors-after-upgrading-postgresql-to-v10).

After upgrading the PG JDBC driver to its latest version (42.2.5 as of now), the IDM works without any issues on PG 10.5 I haven't performed any tests on earlier versions of PG yet).

Bonus: Current PG JDBC driver versions are packaged with a proper OSGi manifests so there is no need to provide our own repackaged and OSGized version of the driver.

Will send PR later...

**Comment by karelmaxa** [comment]
PostgeSQL JDBC driver has been upgraded to the latest version `42.2.18`.
