### ISSUE TITLE
Missing groovy engine in Activiti workflows

### ISSUE THREAD

**Issue by karelmaxa** [WrenSecurity/wrenidm#97]
Wren running the latest build of the master branch, there is an issue with missing Groovy engine in the Activiti workflow.

Steps to reproduce:
- Deploy Wren:IdM `6.0.0-SNAPSHOT` (revision `f7236ce`)
- Run sample/sample9  `./startup.sh -p samples/sample9`
- Follow instructions in `samples/sample9/README`
- Approval of the workflow in section *Option 1: Using the UI* will produce the stacktrace bellow:

```
May 10, 2021 12:50:35 PM org.forgerock.openidm.servlet.internal.ServletConnectionFactory$3 handleException
WARNING: Resource exception: 500 Internal Server Error: "Can't find scripting engine for 'groovy'"
org.forgerock.json.resource.InternalServerErrorException: Can't find scripting engine for 'groovy'
        at org.forgerock.openidm.workflow.activiti.impl.TaskInstanceResource.actionInstance(TaskInstanceResource.java:123)
        at org.forgerock.json.resource.InterfaceCollectionInstance.handleAction(InterfaceCollectionInstance.java:34)
        at org.forgerock.json.resource.FilterChain$Cursor.handleAction(FilterChain.java:63)
        at org.forgerock.json.resource.Resources$CollectionInstanceIdContextFilter.filterAction(Resources.java:500)
        at org.forgerock.json.resource.FilterChain$Cursor.handleAction(FilterChain.java:61)
        at org.forgerock.json.resource.FilterChain.handleAction(FilterChain.java:230)
        at org.forgerock.json.resource.Router.handleAction(Router.java:258)
        at org.forgerock.json.resource.Router.handleAction(Router.java:258)
        at org.forgerock.openidm.workflow.activiti.impl.ActivitiResource.handleAction(ActivitiResource.java:73)
        at org.forgerock.openidm.workflow.activiti.impl.ActivitiServiceImpl.handleAction(ActivitiServiceImpl.java:218)
        at org.forgerock.json.resource.Router.handleAction(Router.java:258)
        at org.forgerock.json.resource.FilterChain$Cursor.handleAction(FilterChain.java:63)
        at org.forgerock.json.resource.Filters$ConditionalFilter.filterAction(Filters.java:52)
        at org.forgerock.json.resource.FilterChain$Cursor.handleAction(FilterChain.java:61)
        at org.forgerock.json.resource.Filters$ConditionalFilter.filterAction(Filters.java:52)
        at org.forgerock.json.resource.FilterChain$Cursor.handleAction(FilterChain.java:61)
        at org.forgerock.openidm.filter.ScriptedFilter$1.apply(ScriptedFilter.java:92)
        at org.forgerock.openidm.filter.ScriptedFilter$1.apply(ScriptedFilter.java:89)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:255)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:244)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:223)
        at org.forgerock.openidm.filter.ScriptedFilter.filterRequest(ScriptedFilter.java:192)
        at org.forgerock.openidm.filter.ScriptedFilter.filterAction(ScriptedFilter.java:88)
        at org.forgerock.json.resource.Filters$ConditionalFilter.filterAction(Filters.java:50)
        at org.forgerock.json.resource.FilterChain$Cursor.handleAction(FilterChain.java:61)
        at org.forgerock.openidm.audit.filter.AuditFilter$1.apply(AuditFilter.java:130)
        at org.forgerock.openidm.audit.filter.AuditFilter$1.apply(AuditFilter.java:127)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:255)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:244)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:223)
        at org.forgerock.openidm.audit.filter.AuditFilter.logAuditAccessEntry(AuditFilter.java:251)
        at org.forgerock.openidm.audit.filter.AuditFilter.filterAction(AuditFilter.java:126)
        at org.forgerock.openidm.filter.MutableFilterDecorator.filterAction(MutableFilterDecorator.java:74)
        at org.forgerock.json.resource.Filters$ConditionalFilter.filterAction(Filters.java:50)
        at org.forgerock.json.resource.FilterChain$Cursor.handleAction(FilterChain.java:61)
        at org.forgerock.openidm.servlet.internal.ServletConnectionFactory$4.filterAction(ServletConnectionFactory.java:456)
        at org.forgerock.json.resource.FilterChain$Cursor.handleAction(FilterChain.java:61)
        at org.forgerock.openidm.filter.PassthroughFilter.filterAction(PassthroughFilter.java:50)
        at org.forgerock.openidm.filter.MutableFilterDecorator.filterAction(MutableFilterDecorator.java:74)
        at org.forgerock.openidm.filter.MutableFilterDecorator.filterAction(MutableFilterDecorator.java:74)
        at org.forgerock.json.resource.FilterChain$Cursor.handleAction(FilterChain.java:61)
        at org.forgerock.openidm.filter.PassthroughFilter.filterAction(PassthroughFilter.java:50)
        at org.forgerock.openidm.filter.MutableFilterDecorator.filterAction(MutableFilterDecorator.java:74)
        at org.forgerock.json.resource.FilterChain$Cursor.handleAction(FilterChain.java:61)
        at org.forgerock.json.resource.FilterChain.handleAction(FilterChain.java:230)
        at org.forgerock.json.resource.InternalConnection.actionAsync(InternalConnection.java:37)
        at org.forgerock.json.resource.AbstractConnectionWrapper.actionAsync(AbstractConnectionWrapper.java:82)
        at org.forgerock.openidm.servlet.internal.ServletConnectionFactory$1$1.actionAsync(ServletConnectionFactory.java:353)
        at org.forgerock.json.resource.http.RequestRunner.visitActionRequest(RequestRunner.java:149)
        at org.forgerock.json.resource.http.RequestRunner.visitActionRequest(RequestRunner.java:95)
        at org.forgerock.json.resource.Requests$ActionRequestImpl.accept(Requests.java:185)
        at org.forgerock.json.resource.http.RequestRunner.handleResult(RequestRunner.java:141)
        at org.forgerock.json.resource.http.HttpAdapter$1.apply(HttpAdapter.java:725)
        at org.forgerock.json.resource.http.HttpAdapter$1.apply(HttpAdapter.java:722)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:255)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:244)
        at org.forgerock.json.resource.http.HttpAdapter.doRequest(HttpAdapter.java:722)
        at org.forgerock.json.resource.http.HttpAdapter.doAction(HttpAdapter.java:627)
        at org.forgerock.json.resource.http.HttpAdapter.handle(HttpAdapter.java:291)
        at org.forgerock.http.handler.Handlers$HandlerDescribableAsDescribableHandler.handle(Handlers.java:154)
        at org.forgerock.http.filter.OptionsFilter.filter(OptionsFilter.java:77)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.swagger.OpenApiRequestFilter.filter(OpenApiRequestFilter.java:70)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.grantAccess(AuthenticationFramework.java:201)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.access$200(AuthenticationFramework.java:64)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework$2.apply(AuthenticationFramework.java:193)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework$2.apply(AuthenticationFramework.java:186)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:255)
        at org.forgerock.util.promise.Promises$CompletedPromise.thenAsync(Promises.java:244)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.validateRequest(AuthenticationFramework.java:151)
        at org.forgerock.caf.authentication.framework.AuthenticationFramework.processMessage(AuthenticationFramework.java:141)
        at org.forgerock.caf.authentication.framework.AuthenticationFilter.filter(AuthenticationFilter.java:92)
        at org.forgerock.openidm.auth.AuthFilterWrapper.filter(AuthFilterWrapper.java:95)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.filter.TransactionIdInboundFilter.filter(TransactionIdInboundFilter.java:60)
        at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:61)
        at org.forgerock.http.servlet.HttpFrameworkServlet.service(HttpFrameworkServlet.java:237)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:301)
        at jdk.internal.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.forgerock.openidm.servletregistration.impl.ServletRegistrationSingleton$FilterProxy.invoke(ServletRegistrationSingleton.java:299)
        at com.sun.proxy.$Proxy53.doFilter(Unknown Source)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:257)
        at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:220)
        at jdk.internal.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.forgerock.openidm.servletregistration.impl.ServletRegistrationSingleton$FilterProxy.invoke(ServletRegistrationSingleton.java:299)
        at com.sun.proxy.$Proxy53.doFilter(Unknown Source)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:72)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:287)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.activiti.engine.ActivitiException: Can't find scripting engine for 'groovy'
        at org.activiti.engine.impl.scripting.ScriptingEngines.getEngineByName(ScriptingEngines.java:124)
        at org.activiti.engine.impl.scripting.ScriptingEngines.evaluate(ScriptingEngines.java:85)
        at org.activiti.osgi.OsgiScriptingEngines.evaluate(OsgiScriptingEngines.java:60)
        at org.activiti.osgi.OsgiScriptingEngines.evaluate(OsgiScriptingEngines.java:47)
        at org.activiti.engine.impl.bpmn.behavior.ScriptTaskActivityBehavior.execute(ScriptTaskActivityBehavior.java:78)
        at org.activiti.engine.impl.pvm.runtime.AtomicOperationActivityExecute.execute(AtomicOperationActivityExecute.java:60)
        at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:652)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:645)
        at org.activiti.engine.impl.pvm.runtime.AtomicOperationTransitionNotifyListenerStart.eventNotificationsCompleted(AtomicOperationTransitionNotifyListenerStart.java:52)
        at org.activiti.engine.impl.pvm.runtime.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:58)
        at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:652)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:645)
        at org.activiti.engine.impl.pvm.runtime.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:51)
        at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:652)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:645)
        at org.activiti.engine.impl.pvm.runtime.AtomicOperationTransitionCreateScope.execute(AtomicOperationTransitionCreateScope.java:49)
        at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:652)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:645)
        at org.activiti.engine.impl.pvm.runtime.AtomicOperationTransitionNotifyListenerTake.execute(AtomicOperationTransitionNotifyListenerTake.java:80)
        at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:652)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:645)
        at org.activiti.engine.impl.pvm.runtime.AtomicOperationTransitionDestroyScope.execute(AtomicOperationTransitionDestroyScope.java:132)
        at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:652)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:645)
        at org.activiti.engine.impl.pvm.runtime.AtomicOperationTransitionNotifyListenerEnd.eventNotificationsCompleted(AtomicOperationTransitionNotifyListenerEnd.java:35)
        at org.activiti.engine.impl.pvm.runtime.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:58)
        at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:652)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:645)
        at org.activiti.engine.impl.pvm.runtime.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:51)
        at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:652)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:645)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.take(ExecutionEntity.java:462)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.take(ExecutionEntity.java:440)
        at org.activiti.engine.impl.bpmn.behavior.BpmnActivityBehavior.performOutgoingBehavior(BpmnActivityBehavior.java:140)
        at org.activiti.engine.impl.bpmn.behavior.BpmnActivityBehavior.performDefaultOutgoingBehavior(BpmnActivityBehavior.java:66)
        at org.activiti.engine.impl.bpmn.behavior.FlowNodeActivityBehavior.leave(FlowNodeActivityBehavior.java:55)
        at org.activiti.engine.impl.bpmn.behavior.AbstractBpmnActivityBehavior.leave(AbstractBpmnActivityBehavior.java:47)
        at org.activiti.engine.impl.bpmn.behavior.UserTaskActivityBehavior.signal(UserTaskActivityBehavior.java:228)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.signal(ExecutionEntity.java:419)
        at org.activiti.engine.impl.persistence.entity.TaskEntity.complete(TaskEntity.java:203)
        at org.activiti.engine.impl.cmd.CompleteTaskCmd.execute(CompleteTaskCmd.java:52)
        at org.activiti.engine.impl.cmd.CompleteTaskCmd.execute(CompleteTaskCmd.java:24)
        at org.activiti.engine.impl.cmd.NeedsActiveTaskCmd.execute(NeedsActiveTaskCmd.java:59)
        at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:24)
        at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:57)
        at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31)
        at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40)
        at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35)
        at org.activiti.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:186)
        at org.forgerock.openidm.workflow.activiti.impl.TaskInstanceResource.actionInstance(TaskInstanceResource.java:114)
        ... 116 more
```

**Comment by pavelhoral** [comment]
Would it be possible to write some integration test for this as it is the second time we are facing the same issue?

**Comment by karelmaxa** [comment]
We definitely should to try to create such test. Anyway this issue has been introduced during Java 11 upgrade.

**Comment by pavelhoral** [comment]
Btw. it should be possible to write OSGi "integration" tests as unit tests with the new wrensec-parent where the maven-bundle-plugin is executed during process-classes phase (no need to introduce separate failsafe execution). Not sure what it would take to actually do that in TestNG though... so if the integration test is not easily doable, just fix the bug as the master is broken atm :)

**Comment by krystofNovotny** [comment]
Reverting the Groovy version has solved the problem for now.

I have created tickets #99 and #100 to address the causes of the problem.
